version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: poker
      POSTGRES_USER: poker
      POSTGRES_PASSWORD: poker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
