# Generated by Django 5.2.5 on 2025-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("config", models.JSONField(default=dict)),
                ("stacks", models.JSONField(default=list)),
                ("button", models.IntegerField(default=0)),
                ("hand_counter", models.IntegerField(default=1)),
                ("status", models.CharField(default="running", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
